"""add users table

Revision ID: 2582f040c443
Revises: de23c5b58b86
Create Date: 2023-03-17 14:17:09.844049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2582f040c443"
down_revision = "de23c5b58b86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=240), nullable=False),
        sa.Column("email", sa.String(length=240), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("hashed_password", sa.String(length=240), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
